### ISSUE TITLE
Terragrunt plan fails

### ISSUE THREAD

**Issue by lrh00000** [tf-cloud-modules/terraform-aiven-postgresql#9]
**Describe the bug**
Terraform complains about the optional variables having inappropriate values and fails.
I use Terragrunt which is a wrapper for Terraform.
It spits out these errors:

│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 20, in resource "aiven_pg" "this":
│   20:     shared_buffers_percentage = var.shared_buffers_percentage
│     ├────────────────
│     │ var.shared_buffers_percentage is ""
│ 
│ Inappropriate value for attribute "shared_buffers_percentage": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 23, in resource "aiven_pg" "this":
│   23:     work_mem                  = var.work_mem
│     ├────────────────
│     │ var.work_mem is ""
│ 
│ Inappropriate value for attribute "work_mem": a number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 31, in resource "aiven_pg" "this":
│   31:       port       = var.migration_port
│     ├────────────────
│     │ var.migration_port is ""
│ 
│ Inappropriate value for attribute "port": a number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 32, in resource "aiven_pg" "this":
│   32:       ssl        = var.migration_ssl
│     ├────────────────
│     │ var.migration_ssl is ""
│ 
│ Inappropriate value for attribute "ssl": a bool is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 37, in resource "aiven_pg" "this":
│   37:       autovacuum_analyze_scale_factor     = var.autovacuum_analyze_scale_factor
│     ├────────────────
│     │ var.autovacuum_analyze_scale_factor is ""
│ 
│ Inappropriate value for attribute "autovacuum_analyze_scale_factor": a
│ number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 38, in resource "aiven_pg" "this":
│   38:       autovacuum_analyze_threshold        = var.autovacuum_analyze_threshold
│     ├────────────────
│     │ var.autovacuum_analyze_threshold is ""
│ 
│ Inappropriate value for attribute "autovacuum_analyze_threshold": a number
│ is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 39, in resource "aiven_pg" "this":
│   39:       autovacuum_freeze_max_age           = var.autovacuum_freeze_max_age
│     ├────────────────
│     │ var.autovacuum_freeze_max_age is ""
│ 
│ Inappropriate value for attribute "autovacuum_freeze_max_age": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 40, in resource "aiven_pg" "this":
│   40:       autovacuum_max_workers              = var.autovacuum_max_workers
│     ├────────────────
│     │ var.autovacuum_max_workers is ""
│ 
│ Inappropriate value for attribute "autovacuum_max_workers": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 41, in resource "aiven_pg" "this":
│   41:       autovacuum_naptime                  = var.autovacuum_naptime
│     ├────────────────
│     │ var.autovacuum_naptime is ""
│ 
│ Inappropriate value for attribute "autovacuum_naptime": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 42, in resource "aiven_pg" "this":
│   42:       autovacuum_vacuum_cost_delay        = var.autovacuum_vacuum_cost_delay
│     ├────────────────
│     │ var.autovacuum_vacuum_cost_delay is ""
│ 
│ Inappropriate value for attribute "autovacuum_vacuum_cost_delay": a number
│ is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 43, in resource "aiven_pg" "this":
│   43:       autovacuum_vacuum_cost_limit        = var.autovacuum_vacuum_cost_limit
│     ├────────────────
│     │ var.autovacuum_vacuum_cost_limit is ""
│ 
│ Inappropriate value for attribute "autovacuum_vacuum_cost_limit": a number
│ is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 44, in resource "aiven_pg" "this":
│   44:       autovacuum_vacuum_scale_factor      = var.autovacuum_vacuum_scale_factor
│     ├────────────────
│     │ var.autovacuum_vacuum_scale_factor is ""
│ 
│ Inappropriate value for attribute "autovacuum_vacuum_scale_factor": a
│ number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 45, in resource "aiven_pg" "this":
│   45:       autovacuum_vacuum_threshold         = var.autovacuum_vacuum_threshold
│     ├────────────────
│     │ var.autovacuum_vacuum_threshold is ""
│ 
│ Inappropriate value for attribute "autovacuum_vacuum_threshold": a number
│ is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 46, in resource "aiven_pg" "this":
│   46:       bgwriter_delay                      = var.bgwriter_delay
│     ├────────────────
│     │ var.bgwriter_delay is ""
│ 
│ Inappropriate value for attribute "bgwriter_delay": a number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 47, in resource "aiven_pg" "this":
│   47:       bgwriter_flush_after                = var.bgwriter_flush_after
│     ├────────────────
│     │ var.bgwriter_flush_after is ""
│ 
│ Inappropriate value for attribute "bgwriter_flush_after": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 48, in resource "aiven_pg" "this":
│   48:       bgwriter_lru_maxpages               = var.bgwriter_lru_maxpages
│     ├────────────────
│     │ var.bgwriter_lru_maxpages is ""
│ 
│ Inappropriate value for attribute "bgwriter_lru_maxpages": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 49, in resource "aiven_pg" "this":
│   49:       bgwriter_lru_multiplier             = var.bgwriter_lru_multiplier
│     ├────────────────
│     │ var.bgwriter_lru_multiplier is ""
│ 
│ Inappropriate value for attribute "bgwriter_lru_multiplier": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 50, in resource "aiven_pg" "this":
│   50:       deadlock_timeout                    = var.deadlock_timeout
│     ├────────────────
│     │ var.deadlock_timeout is ""
│ 
│ Inappropriate value for attribute "deadlock_timeout": a number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 52, in resource "aiven_pg" "this":
│   52:       idle_in_transaction_session_timeout = var.idle_in_transaction_session_timeout
│     ├────────────────
│     │ var.idle_in_transaction_session_timeout is ""
│ 
│ Inappropriate value for attribute "idle_in_transaction_session_timeout": a
│ number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 53, in resource "aiven_pg" "this":
│   53:       jit                                 = var.jit
│     ├────────────────
│     │ var.jit is ""
│ 
│ Inappropriate value for attribute "jit": a bool is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 54, in resource "aiven_pg" "this":
│   54:       log_autovacuum_min_duration         = var.log_autovacuum_min_duration
│     ├────────────────
│     │ var.log_autovacuum_min_duration is ""
│ 
│ Inappropriate value for attribute "log_autovacuum_min_duration": a number
│ is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 57, in resource "aiven_pg" "this":
│   57:       log_min_duration_statement          = var.log_min_duration_statement
│     ├────────────────
│     │ var.log_min_duration_statement is ""
│ 
│ Inappropriate value for attribute "log_min_duration_statement": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 58, in resource "aiven_pg" "this":
│   58:       max_files_per_process               = var.max_files_per_process
│     ├────────────────
│     │ var.max_files_per_process is ""
│ 
│ Inappropriate value for attribute "max_files_per_process": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 59, in resource "aiven_pg" "this":
│   59:       max_locks_per_transaction           = var.max_locks_per_transaction
│     ├────────────────
│     │ var.max_locks_per_transaction is ""
│ 
│ Inappropriate value for attribute "max_locks_per_transaction": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 60, in resource "aiven_pg" "this":
│   60:       max_logical_replication_workers     = var.max_logical_replication_workers
│     ├────────────────
│     │ var.max_logical_replication_workers is ""
│ 
│ Inappropriate value for attribute "max_logical_replication_workers": a
│ number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 61, in resource "aiven_pg" "this":
│   61:       max_parallel_workers                = var.max_parallel_workers
│     ├────────────────
│     │ var.max_parallel_workers is ""
│ 
│ Inappropriate value for attribute "max_parallel_workers": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 62, in resource "aiven_pg" "this":
│   62:       max_parallel_workers_per_gather     = var.max_parallel_workers_per_gather
│     ├────────────────
│     │ var.max_parallel_workers_per_gather is ""
│ 
│ Inappropriate value for attribute "max_parallel_workers_per_gather": a
│ number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 63, in resource "aiven_pg" "this":
│   63:       max_pred_locks_per_transaction      = var.max_pred_locks_per_transaction
│     ├────────────────
│     │ var.max_pred_locks_per_transaction is ""
│ 
│ Inappropriate value for attribute "max_pred_locks_per_transaction": a
│ number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 64, in resource "aiven_pg" "this":
│   64:       max_prepared_transactions           = var.max_prepared_transactions
│     ├────────────────
│     │ var.max_prepared_transactions is ""
│ 
│ Inappropriate value for attribute "max_prepared_transactions": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 65, in resource "aiven_pg" "this":
│   65:       max_replication_slots               = var.max_replication_slots
│     ├────────────────
│     │ var.max_replication_slots is ""
│ 
│ Inappropriate value for attribute "max_replication_slots": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 66, in resource "aiven_pg" "this":
│   66:       max_slot_wal_keep_size              = var.max_slot_wal_keep_size
│     ├────────────────
│     │ var.max_slot_wal_keep_size is ""
│ 
│ Inappropriate value for attribute "max_slot_wal_keep_size": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 67, in resource "aiven_pg" "this":
│   67:       max_stack_depth                     = var.max_stack_depth
│     ├────────────────
│     │ var.max_stack_depth is ""
│ 
│ Inappropriate value for attribute "max_stack_depth": a number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 68, in resource "aiven_pg" "this":
│   68:       max_standby_archive_delay           = var.max_standby_archive_delay
│     ├────────────────
│     │ var.max_standby_archive_delay is ""
│ 
│ Inappropriate value for attribute "max_standby_archive_delay": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 69, in resource "aiven_pg" "this":
│   69:       max_standby_streaming_delay         = var.max_standby_streaming_delay
│     ├────────────────
│     │ var.max_standby_streaming_delay is ""
│ 
│ Inappropriate value for attribute "max_standby_streaming_delay": a number
│ is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 70, in resource "aiven_pg" "this":
│   70:       max_wal_senders                     = var.max_wal_senders
│     ├────────────────
│     │ var.max_wal_senders is ""
│ 
│ Inappropriate value for attribute "max_wal_senders": a number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 71, in resource "aiven_pg" "this":
│   71:       max_worker_processes                = var.max_worker_processes
│     ├────────────────
│     │ var.max_worker_processes is ""
│ 
│ Inappropriate value for attribute "max_worker_processes": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 72, in resource "aiven_pg" "this":
│   72:       pg_partman_bgw__dot__interval       = var.pg_partman_bgw__dot__interval
│     ├────────────────
│     │ var.pg_partman_bgw__dot__interval is ""
│ 
│ Inappropriate value for attribute "pg_partman_bgw__dot__interval": a number
│ is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 75, in resource "aiven_pg" "this":
│   75:       temp_file_limit                     = var.temp_file_limit
│     ├────────────────
│     │ var.temp_file_limit is ""
│ 
│ Inappropriate value for attribute "temp_file_limit": a number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 77, in resource "aiven_pg" "this":
│   77:       track_activity_query_size           = var.track_activity_query_size
│     ├────────────────
│     │ var.track_activity_query_size is ""
│ 
│ Inappropriate value for attribute "track_activity_query_size": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 81, in resource "aiven_pg" "this":
│   81:       wal_sender_timeout                  = var.wal_sender_timeout
│     ├────────────────
│     │ var.wal_sender_timeout is ""
│ 
│ Inappropriate value for attribute "wal_sender_timeout": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 82, in resource "aiven_pg" "this":
│   82:       wal_writer_delay                    = var.wal_writer_delay
│     ├────────────────
│     │ var.wal_writer_delay is ""
│ 
│ Inappropriate value for attribute "wal_writer_delay": a number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 86, in resource "aiven_pg" "this":
│   86:       autodb_idle_timeout       = var.autodb_idle_timeout
│     ├────────────────
│     │ var.autodb_idle_timeout is ""
│ 
│ Inappropriate value for attribute "autodb_idle_timeout": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 87, in resource "aiven_pg" "this":
│   87:       autodb_max_db_connections = var.autodb_max_db_connections
│     ├────────────────
│     │ var.autodb_max_db_connections is ""
│ 
│ Inappropriate value for attribute "autodb_max_db_connections": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 89, in resource "aiven_pg" "this":
│   89:       autodb_pool_size          = var.autodb_pool_size
│     ├────────────────
│     │ var.autodb_pool_size is ""
│ 
│ Inappropriate value for attribute "autodb_pool_size": a number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 91, in resource "aiven_pg" "this":
│   91:       min_pool_size             = var.min_pool_size
│     ├────────────────
│     │ var.min_pool_size is ""
│ 
│ Inappropriate value for attribute "min_pool_size": a number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 92, in resource "aiven_pg" "this":
│   92:       server_idle_timeout       = var.server_idle_timeout
│     ├────────────────
│     │ var.server_idle_timeout is ""
│ 
│ Inappropriate value for attribute "server_idle_timeout": a number is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 93, in resource "aiven_pg" "this":
│   93:       server_lifetime           = var.server_lifetime
│     ├────────────────
│     │ var.server_lifetime is ""
│ 
│ Inappropriate value for attribute "server_lifetime": a number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 94, in resource "aiven_pg" "this":
│   94:       server_reset_query_always = var.server_reset_query_always
│     ├────────────────
│     │ var.server_reset_query_always is ""
│ 
│ Inappropriate value for attribute "server_reset_query_always": a bool is
│ required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 98, in resource "aiven_pg" "this":
│   98:       max_failover_replication_time_lag = var.max_failover_replication_time_lag
│     ├────────────────
│     │ var.max_failover_replication_time_lag is ""
│ 
│ Inappropriate value for attribute "max_failover_replication_time_lag": a
│ number is required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/postgresql/main.tf line 120, in resource "aiven_pg" "this":
│  120:       max_background_workers = var.max_background_workers
│     ├────────────────
│     │ var.max_background_workers is ""
│ 
│ Inappropriate value for attribute "max_background_workers": a number is
│ required.

**To Reproduce**
terragrunt plan

**Expected behavior**
It should create a postgres database

**Additional context**
Terraform v1.3.5
on darwin_arm64
+ provider registry.terraform.io/aiven/aiven v4.1.0
+ provider registry.terraform.io/hashicorp/aws v4.58.0
+ provider registry.terraform.io/hashicorp/google v4.56.0

**Comment by andreilapkin** [comment]
Resolved by https://github.com/tf-cloud-modules/terraform-aiven-postgresql/pull/10 (if you need provider version between 4.0.0 and 5.0.0)
Or you can use version 1.0.4 of module if you need to use provider version between 3.0.0 and 4.0.0
